package model

type ParticipantDTO struct {
	Assists                        int           `json:"assists"`
	BaronKills                     int           `json:"baronKills"`
	BountyLevel                    int           `json:"bountyLevel"`
	Challenges                     ChallengesDTO `json:"challenges"`
	ChampExperience                int           `json:"champExperience"`
	ChampLevel                     int           `json:"champLevel"`
	ChampionId                     int           `json:"championId"`
	ChampionName                   string        `json:"championName"`
	ChampionTransform              int           `json:"championTransform"`
	ConsumablesPurchased           int           `json:"consumablesPurchased"`
	DamageDealtToBuildings         int           `json:"damageDealtToBuildings"`
	DamageDealtToObjectives        int           `json:"damageDealtToObjectives"`
	DamageDealtToTurrets           int           `json:"damageDealtToTurrets"`
	DamageSelfMitigated            int           `json:"damageSelfMitigated"`
	Deaths                         int           `json:"deaths"`
	DetectorWardsPlaced            int           `json:"detectorWardsPlaced"`
	DoubleKills                    int           `json:"doubleKills"`
	DragonKills                    int           `json:"dragonKills"`
	FirstBloodAssist               bool          `json:"firstBloodAssist"`
	FirstBloodKill                 bool          `json:"firstBloodKill"`
	FirstTowerAssist               bool          `json:"firstTowerAssist"`
	FirstTowerKill                 bool          `json:"firstTowerKill"`
	GameEndedInEarlySurrender      bool          `json:"gameEndedInEarlySurrender"`
	GameEndedInSurrender           bool          `json:"gameEndedInSurrender"`
	GoldEarned                     int           `json:"goldEarned"`
	GoldSpent                      int           `json:"goldSpent"`
	IndividualPosition             string        `json:"individualPosition"`
	InhibitorKills                 int           `json:"inhibitorKills"`
	InhibitorTakedowns             int           `json:"inhibitorTakedowns"`
	InhibitorsLost                 int           `json:"inhibitorsLost"`
	Item0                          int           `json:"item0"`
	Item1                          int           `json:"item1"`
	Item2                          int           `json:"item2"`
	Item3                          int           `json:"item3"`
	Item4                          int           `json:"item4"`
	Item5                          int           `json:"item5"`
	Item6                          int           `json:"item6"`
	ItemsPurchased                 int           `json:"itemsPurchased"`
	KillingSprees                  int           `json:"killingSprees"`
	Kills                          int           `json:"kills"`
	Lane                           string        `json:"lane"`
	LargestCriticalStrike          int           `json:"largestCriticalStrike"`
	LargestKillingSpree            int           `json:"largestKillingSpree"`
	LargestMultiKill               int           `json:"largestMultiKill"`
	LongestTimeSpentLiving         int           `json:"longestTimeSpentLiving"`
	MagicDamageDealt               int           `json:"magicDamageDealt"`
	MagicDamageDealtToChampions    int           `json:"magicDamageDealtToChampions"`
	MagicDamageTaken               int           `json:"magicDamageTaken"`
	NeutralMinionsKilled           int           `json:"neutralMinionsKilled"`
	NexusKills                     int           `json:"nexusKills"`
	NexusLost                      int           `json:"nexusLost"`
	NexusTakedowns                 int           `json:"nexusTakedowns"`
	ObjectivesStolen               int           `json:"objectivesStolen"`
	ObjectivesStolenAssists        int           `json:"objectivesStolenAssists"`
	ParticipantId                  int           `json:"participantId"`
	PentaKills                     int           `json:"pentaKills"`
	Perks                          PerksDTO      `json:"perks"`
	PhysicalDamageDealt            int           `json:"physicalDamageDealt"`
	PhysicalDamageDealtToChampions int           `json:"physicalDamageDealtToChampions"`
	PhysicalDamageTaken            int           `json:"physicalDamageTaken"`
	ProfileIcon                    int           `json:"profileIcon"`
	Puuid                          string        `json:"puuid"`
	QuadraKills                    int           `json:"quadraKills"`
	RiotIdName                     string        `json:"riotIdName"`
	RiotIdTagline                  string        `json:"riotIdTagline"`
	Role                           string        `json:"role"`
	SightWardsBoughtInGame         int           `json:"sightWardsBoughtInGame"`
	Spell1Casts                    int           `json:"spell1Casts"`
	Spell2Casts                    int           `json:"spell2Casts"`
	Spell3Casts                    int           `json:"spell3Casts"`
	Spell4Casts                    int           `json:"spell4Casts"`
	Summoner1Casts                 int           `json:"summoner1Casts"`
	Summoner1Id                    int           `json:"summoner1Id"`
	Summoner2Casts                 int           `json:"summoner2Casts"`
	Summoner2Id                    int           `json:"summoner2Id"`
	SummonerId                     string        `json:"summonerId"`
	SummonerLevel                  int           `json:"summonerLevel"`
	SummonerName                   string        `json:"summonerName"`
	TeamEarlySurrendered           bool          `json:"teamEarlySurrendered"`
	TeamId                         int           `json:"teamId"`
	TeamPosition                   string        `json:"teamPosition"`
	TimeCCingOthers                int           `json:"timeCCingOthers"`
	TimePlayed                     int           `json:"timePlayed"`
	TotalDamageDealt               int           `json:"totalDamageDealt"`
	TotalDamageDealtToChampions    int           `json:"totalDamageDealtToChampions"`
	TotalDamageShieldedOnTeammates int           `json:"totalDamageShieldedOnTeammates"`
	TotalDamageTaken               int           `json:"totalDamageTaken"`
	TotalHeal                      int           `json:"totalHeal"`
	TotalHealsOnTeammates          int           `json:"totalHealsOnTeammates"`
	TotalMinionsKilled             int           `json:"totalMinionsKilled"`
	TotalTimeCCDealt               int           `json:"totalTimeCCDealt"`
	TotalTimeSpentDead             int           `json:"totalTimeSpentDead"`
	TotalUnitsHealed               int           `json:"totalUnitsHealed"`
	TripleKills                    int           `json:"tripleKills"`
	TrueDamageDealt                int           `json:"trueDamageDealt"`
	TrueDamageDealtToChampions     int           `json:"trueDamageDealtToChampions"`
	TrueDamageTaken                int           `json:"trueDamageTaken"`
	TurretKills                    int           `json:"turretKills"`
	TurretTakedowns                int           `json:"turretTakedowns"`
	TurretsLost                    int           `json:"turretsLost"`
	UnrealKills                    int           `json:"unrealKills"`
	VisionScore                    int           `json:"visionScore"`
	VisionWardsBoughtInGame        int           `json:"visionWardsBoughtInGame"`
	WardsKilled                    int           `json:"wardsKilled"`
	WardsPlaced                    int           `json:"wardsPlaced"`
	Win                            bool          `json:"win"`
}
